/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillRouteImport } from './routes/_layout/skill'
import { Route as LayoutRecentRouteImport } from './routes/_layout/recent'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutExploreRouteImport } from './routes/_layout/explore'
import { Route as LayoutComponentsRouteImport } from './routes/_layout/components'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutWSlugRouteImport } from './routes/_layout/w/$slug'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/admin'
import { Route as LayoutAppsAccountIdIndexRouteImport } from './routes/_layout/apps/$accountId/index'
import { Route as LayoutAuthenticatedSettingsIndexRouteImport } from './routes/_layout/_authenticated/settings/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutWSlugHistoryRouteImport } from './routes/_layout/w/$slug/history'
import { Route as LayoutWSlugEditRouteImport } from './routes/_layout/w/$slug/edit'
import { Route as LayoutAppsAccountIdGatewayIdRouteImport } from './routes/_layout/apps/$accountId/$gatewayId'
import { Route as LayoutAuthenticatedWikiNewRouteImport } from './routes/_layout/_authenticated/wiki/new'
import { Route as LayoutAuthenticatedSettingsSecurityRouteImport } from './routes/_layout/_authenticated/settings/security'
import { Route as LayoutAuthenticatedSettingsProfileRouteImport } from './routes/_layout/_authenticated/settings/profile'
import { Route as LayoutAuthenticatedSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/settings/auth-methods'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/organizations/$slug'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRoute = LayoutSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecentRoute = LayoutRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComponentsRoute = LayoutComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWSlugRoute = LayoutWSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAppsAccountIdIndexRoute =
  LayoutAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedSettingsIndexRoute =
  LayoutAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutWSlugHistoryRoute = LayoutWSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutWSlugRoute,
} as any)
const LayoutWSlugEditRoute = LayoutWSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutWSlugRoute,
} as any)
const LayoutAppsAccountIdGatewayIdRoute =
  LayoutAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedWikiNewRoute =
  LayoutAuthenticatedWikiNewRouteImport.update({
    id: '/wiki/new',
    path: '/wiki/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsSecurityRoute =
  LayoutAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsProfileRoute =
  LayoutAuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsAuthMethodsRoute =
  LayoutAuthenticatedSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsSlugRoute =
  LayoutAuthenticatedOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/components': typeof LayoutComponentsRoute
  '/explore': typeof LayoutExploreRoute
  '/login': typeof LayoutLoginRoute
  '/recent': typeof LayoutRecentRoute
  '/skill': typeof LayoutSkillRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/w/$slug': typeof LayoutWSlugRouteWithChildren
  '/apps/': typeof LayoutAppsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/wiki/new': typeof LayoutAuthenticatedWikiNewRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/w/$slug/edit': typeof LayoutWSlugEditRoute
  '/w/$slug/history': typeof LayoutWSlugHistoryRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/components': typeof LayoutComponentsRoute
  '/explore': typeof LayoutExploreRoute
  '/login': typeof LayoutLoginRoute
  '/recent': typeof LayoutRecentRoute
  '/skill': typeof LayoutSkillRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/w/$slug': typeof LayoutWSlugRouteWithChildren
  '/apps': typeof LayoutAppsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/wiki/new': typeof LayoutAuthenticatedWikiNewRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/w/$slug/edit': typeof LayoutWSlugEditRoute
  '/w/$slug/history': typeof LayoutWSlugHistoryRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps/$accountId': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/components': typeof LayoutComponentsRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/recent': typeof LayoutRecentRoute
  '/_layout/skill': typeof LayoutSkillRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRoute
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/w/$slug': typeof LayoutWSlugRouteWithChildren
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/_layout/_authenticated/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/_layout/_authenticated/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/_layout/_authenticated/wiki/new': typeof LayoutAuthenticatedWikiNewRoute
  '/_layout/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/_layout/w/$slug/edit': typeof LayoutWSlugEditRoute
  '/_layout/w/$slug/history': typeof LayoutWSlugHistoryRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/_layout/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/components'
    | '/explore'
    | '/login'
    | '/recent'
    | '/skill'
    | '/admin'
    | '/home'
    | '/settings'
    | '/w/$slug'
    | '/apps/'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/wiki/new'
    | '/apps/$accountId/$gatewayId'
    | '/w/$slug/edit'
    | '/w/$slug/history'
    | '/organizations/'
    | '/settings/'
    | '/apps/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/components'
    | '/explore'
    | '/login'
    | '/recent'
    | '/skill'
    | '/admin'
    | '/home'
    | '/w/$slug'
    | '/apps'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/wiki/new'
    | '/apps/$accountId/$gatewayId'
    | '/w/$slug/edit'
    | '/w/$slug/history'
    | '/organizations'
    | '/settings'
    | '/apps/$accountId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/components'
    | '/_layout/explore'
    | '/_layout/login'
    | '/_layout/recent'
    | '/_layout/skill'
    | '/_layout/'
    | '/_layout/_authenticated/admin'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/settings'
    | '/_layout/w/$slug'
    | '/_layout/apps/'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/organizations/$slug'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/settings/auth-methods'
    | '/_layout/_authenticated/settings/profile'
    | '/_layout/_authenticated/settings/security'
    | '/_layout/_authenticated/wiki/new'
    | '/_layout/apps/$accountId/$gatewayId'
    | '/_layout/w/$slug/edit'
    | '/_layout/w/$slug/history'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/settings/'
    | '/_layout/apps/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill': {
      id: '/_layout/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recent': {
      id: '/_layout/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof LayoutRecentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/components': {
      id: '/_layout/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof LayoutComponentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/w/$slug': {
      id: '/_layout/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof LayoutWSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/apps/$accountId/': {
      id: '/_layout/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings/': {
      id: '/_layout/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/w/$slug/history': {
      id: '/_layout/w/$slug/history'
      path: '/history'
      fullPath: '/w/$slug/history'
      preLoaderRoute: typeof LayoutWSlugHistoryRouteImport
      parentRoute: typeof LayoutWSlugRoute
    }
    '/_layout/w/$slug/edit': {
      id: '/_layout/w/$slug/edit'
      path: '/edit'
      fullPath: '/w/$slug/edit'
      preLoaderRoute: typeof LayoutWSlugEditRouteImport
      parentRoute: typeof LayoutWSlugRoute
    }
    '/_layout/apps/$accountId/$gatewayId': {
      id: '/_layout/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/wiki/new': {
      id: '/_layout/_authenticated/wiki/new'
      path: '/wiki/new'
      fullPath: '/wiki/new'
      preLoaderRoute: typeof LayoutAuthenticatedWikiNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings/security': {
      id: '/_layout/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/profile': {
      id: '/_layout/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/auth-methods': {
      id: '/_layout/_authenticated/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$slug': {
      id: '/_layout/_authenticated/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsAuthMethodsRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  LayoutAuthenticatedSettingsProfileRoute: typeof LayoutAuthenticatedSettingsProfileRoute
  LayoutAuthenticatedSettingsSecurityRoute: typeof LayoutAuthenticatedSettingsSecurityRoute
  LayoutAuthenticatedSettingsIndexRoute: typeof LayoutAuthenticatedSettingsIndexRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsAuthMethodsRoute:
      LayoutAuthenticatedSettingsAuthMethodsRoute,
    LayoutAuthenticatedSettingsProfileRoute:
      LayoutAuthenticatedSettingsProfileRoute,
    LayoutAuthenticatedSettingsSecurityRoute:
      LayoutAuthenticatedSettingsSecurityRoute,
    LayoutAuthenticatedSettingsIndexRoute:
      LayoutAuthenticatedSettingsIndexRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRoute
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
  LayoutAuthenticatedOrganizationsSlugRoute: typeof LayoutAuthenticatedOrganizationsSlugRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedWikiNewRoute: typeof LayoutAuthenticatedWikiNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRoute,
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
  LayoutAuthenticatedOrganizationsSlugRoute:
    LayoutAuthenticatedOrganizationsSlugRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedWikiNewRoute: LayoutAuthenticatedWikiNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutWSlugRouteChildren {
  LayoutWSlugEditRoute: typeof LayoutWSlugEditRoute
  LayoutWSlugHistoryRoute: typeof LayoutWSlugHistoryRoute
}

const LayoutWSlugRouteChildren: LayoutWSlugRouteChildren = {
  LayoutWSlugEditRoute: LayoutWSlugEditRoute,
  LayoutWSlugHistoryRoute: LayoutWSlugHistoryRoute,
}

const LayoutWSlugRouteWithChildren = LayoutWSlugRoute._addFileChildren(
  LayoutWSlugRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutComponentsRoute: typeof LayoutComponentsRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutRecentRoute: typeof LayoutRecentRoute
  LayoutSkillRoute: typeof LayoutSkillRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWSlugRoute: typeof LayoutWSlugRouteWithChildren
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutAppsAccountIdGatewayIdRoute: typeof LayoutAppsAccountIdGatewayIdRoute
  LayoutAppsAccountIdIndexRoute: typeof LayoutAppsAccountIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutComponentsRoute: LayoutComponentsRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutRecentRoute: LayoutRecentRoute,
  LayoutSkillRoute: LayoutSkillRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWSlugRoute: LayoutWSlugRouteWithChildren,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutAppsAccountIdGatewayIdRoute: LayoutAppsAccountIdGatewayIdRoute,
  LayoutAppsAccountIdIndexRoute: LayoutAppsAccountIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
